apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    note: not_important
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
  restartPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    note: important
  name: pod2
spec:
  containers:
    - image: fluent/fluent-bit
      name: fluent-bit
      resources: {}
    - image: nginx
      name: nginx
      resources: {}
  restartPolicy: Always
